# select base image
FROM python:3.8

# Set working directory 
WORKDIR /model

COPY requirements.txt .

RUN pip3 install --no-cache-dir -r requirements.txt

COPY ./scripts ./scripts

CMD ["python", "./src"]