FROM python:3.8.12

# Set working directory 
#WORKDIR /the/workdir/path

# Create conda environment from yaml file
COPY environment.yml  .
RUN conda env create -f environment.yml

# Activate environment
RUN conda activate thesis

# Set environment variables
ENV PYTHONUNBUFFERED=TRUE
ENV PYTHONDONTWRITEBYTECODE=TRUE
ENV PATH="/opt/program:${PATH}"

# Set up the program in the image
COPY src /__main__.py

ENTRYPOINT ["python", "run"]