name: thesis
channels:
  - conda-forge
dependencies:
  - python=3.8
  - matplotlib==3.3.1
  - numpy==1.21.2
  - gpytorch==1.6.0
  - psycopg2==2.8.6
  - scipy==1.7.3
  - SQLAlchemy==1.3.19
  - tqdm==4.62.3
  - black==22.1.0
  - requests==2.27.1
  - pyparsing==3.0.4
  - pandas==1.1.3
  - torch==1.10.2
  - seaborn==0.11.0
  - pycaret==2.3.9
  - scikit_learn==1.0.2